version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 580801916917  # your AWS account ID here
    IMAGE_NAME: bluegreen

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Installing Node dependencies...
      - npm install
      - echo Setting up Docker daemon...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
      - docker tag $IMAGE_URI $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_URI
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"bluegreen","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - taskdef.json
    - imagedefinitions.json
